version: '2'
services:

  web:
    container_name: 'web'
    build:
      context: ./web-ui
    ports:
      - "3000:3000"
      - "35729:35729"
    networks:
      - api
    depends_on:
      - api
    volumes:
        - ./web-ui:/app

  api:
    container_name: 'api'
    build:
      context: ./graphql
    ports:
      - "3001:3001"
    environment:
      GRAPHQL_PORT: 3001
      ANIME_BASE_URL: 'https://api.jikan.me'
      NODE_ENV: 'development'
      MONGO_URL: 'mongodb://mongo:27017'
    volumes:
      - ./graphql/config:/app/config
      - ./graphql/src:/app/src
    networks:
      - mongo
      - api
    depends_on:
      - mongo

  mongo:
    image: mongo:3.0.0
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    # volumes:
    #   - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo

networks:
  mongo:
  api:
